[package]
name = "frontend-minify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["cargo"] }
tokio = { version = "1.40.0", features = ["full"] }
walkdir = "2.5.0"
